services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Outbox\Application\UseCase\OutboxEventHandler:
        arguments:
          [ '@App\Outbox\Model\WriteOutboxStorage' ]

    App\Outbox\Model\WriteOutboxStorage:
        class: App\Outbox\Infrastructure\Persistence\Doctrine\OutboxRepository