parameters:
    kafka.broker.list: '%env(KAFKA_BROKER_LIST)%'
    kafka.consumer.group: '%env(KAFKA_GROUP_ID)%'
    kafka.topic.prefix: '%env(KAFKA_TOPIC_PREFIX)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Core\Worker\Kafka\KafkaWorker:
        arguments:
            [
                '@App\Core\Infrastructure\Kafka\Consumer\KafkaConsumerService'
            ]

    App\Core\Infrastructure\Kafka\Consumer\KafkaConsumerService:
        arguments:
            - '%kafka.broker.list%'
            - '%kafka.consumer.group%'
            - '%kafka.topic.prefix%'

    App\Lottery\Model\ReadLotteryStorage:
        public: true
        class: App\Lottery\Persistence\Doctrine\LotteryRepository

    App\Core\ExceptionListener\RequestExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
