parameters:
    kafka.broker.list: '%env(KAFKA_BROKER_LIST)%'
    kafka.consumer.group: '%env(KAFKA_GROUP_ID)%'
    kafka.topic.prefix: '%env(KAFKA_TOPIC_PREFIX)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Core\Worker\Kafka\KafkaWorker:
        arguments:
            [
                '@App\Core\Infrastructure\Kafka\Consumer\KafkaConsumerService',
                '@React\EventLoop\LoopInterface',
                '@App\Lottery\Application\UseCase\LotteryCreateHandler'
            ]

    App\Core\Infrastructure\Kafka\Consumer\KafkaConsumerService:
        arguments:
            - '%kafka.broker.list%'
            - '%kafka.consumer.group%'
            - '%kafka.topic.prefix%'

    App\Core\Infrastructure\Kafka\Producer\OutboxKafkaProduceService:
        arguments:
            - '%kafka.topic.prefix%'
            - '%kafka.broker.list%'

    App\Lottery\Model\ReadLotteryStorage:
        public: true
        class: App\Lottery\Infrastructure\Persistence\Doctrine\LotteryRepository

    App\Lottery\Model\WriteLotteryStorage:
        class: App\Lottery\Infrastructure\Persistence\Doctrine\LotteryRepository

    App\Core\ExceptionListener\RequestExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    App\Lottery\Application\UseCase\LotteryCreateHandler: ~
    React\EventLoop\StreamSelectLoop: ~
    React\EventLoop\LoopInterface: '@React\EventLoop\StreamSelectLoop'

imports:
    - { resource:  ../src/Outbox/config/services.yaml }
